apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.host }}-cert
spec:
  dnsNames:
    - {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.host }}
  commonName: {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.host }}
  secretName: {{ .Chart.Name }}.{{ .Release.Namespace }}.{{ .Values.ingress.host }}-cert
  issuerRef:
    name: {{ .Chart.Name }}.letsencrypt
